export const CREATE_FORM = "CREATE_FORM";
export const LOAD_FORMS_SUCCESS = "LOAD_FORMS_SUCCESS";
export const LOAD_SENIORS_SUCCESS = "LOAD_SENIORS_SUCCESS";
export const LOAD_HANDYMANS_SUCCESS = "LOAD_HANDYMANS_SUCCESS";
export const LOAD_FORMSTATUSES_SUCCESS = "LOAD_FORMSTATUSES_SUCCESS";