export const CREATE_FORM = "CREATE_FORM";
export const LOAD_FORMS_SUCCESS = "LOAD_FORMS_SUCCESS";
export const LOAD_SENIORS_SUCCESS = "LOAD_SENIORS_SUCCESS";
export const LOAD_HANDYMANS_SUCCESS = "LOAD_HANDYMANS_SUCCESS";
export const LOAD_FORMSTATUSES_SUCCESS = "LOAD_FORMSTATUSES_SUCCESS";
export const CREATE_FORM_SUCCESS = "CREATE_FORM_SUCCESS";
export const UPDATE_FORM_SUCCESS = "UPDATE_FORM_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";