export const LOAD_FORMS_SUCCESS = "LOAD_FORMS_SUCCESS";
export const CREATE_FORM_SUCCESS = "CREATE_FORM_SUCCESS";
export const UPDATE_FORM_SUCCESS = "UPDATE_FORM_SUCCESS";
export const DELETE_FORM_OPTIMISTIC = "DELETE_FORM_OPTIMISTIC";

export const LOAD_SENIORS_SUCCESS = "LOAD_SENIORS_SUCCESS";
export const CREATE_SENIOR_SUCCESS = "CREATE_SENIOR_SUCCESS";
export const UPDATE_SENIOR_SUCCESS = "UPDATE_SENIOR_SUCCESS";
export const DELETE_SENIOR_OPTIMISTIC = "DELETE_SENIOR_OPTIMISTIC";

export const LOAD_BILLS_SUCCESS = "LOAD_BILLS_SUCCESS";
export const CREATE_BILL_SUCCESS = "CREATE_BILL_SUCCESS";
export const UPDATE_BILL_SUCCESS = "UPDATE_BILL_SUCCESS";
export const DELETE_BILL_OPTIMISTIC = "DELETE_BILL_OPTIMISTIC";

export const LOAD_HANDYMANS_SUCCESS = "LOAD_HANDYMANS_SUCCESS";

export const LOAD_FORMSTATUSES_SUCCESS = "LOAD_FORMSTATUSES_SUCCESS";

export const GET_SUMMARY_ROWS = "GET_SUMMARY_ROWS";
export const SET_SUMMARY_ROWS = "SET_SUMMARY_ROWS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const USER_LOGOUT = "USER_LOGOUT";
